name: modelling-b-venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyvis
  - networkx
  - tqdm
  - PuLP
  - docplex
  - pandas
  - dill
  - numpy
  - openpyxl
  - jupyter
  - ipympl
  - matplotlib
  - matplotlib-inline
  - scipy
  - typing_extensions